# version format
version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      vsversion: 2022
      platform: MSVC 64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      vsversion: 2019
      platform: MSVC 64
      configuration: Release

install:
  - cmd: if %vsversion%==2015
         "Visual Studio 2015.bat"
  - cmd: if %vsversion%==2017
         "Visual Studio 2017.bat"
  - cmd: if %vsversion%==2019
         "Visual Studio 2019.bat"
  - cmd: if %vsversion%==2022
         "Visual Studio 2022.bat"
  - sh: if [[ $APPVEYOR_BUILD_WORKER_IMAGE = Ubuntu ]]; then ./Linux.sh; fi;
  - sh: if [[ $APPVEYOR_BUILD_WORKER_IMAGE = macOS ]]; then ./Xcode.sh; fi;

build_script:
  - cmd: if %vsversion%==2015
         msbuild "C:\projects\crstl\workspace\vs2015\crstl.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: if %vsversion%==2017
         msbuild "C:\projects\crstl\workspace\vs2017\crstl.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: if %vsversion%==2019
         msbuild "C:\projects\crstl\workspace\vs2019\crstl.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: if %vsversion%==2022
         msbuild "C:\projects\crstl\workspace\vs2022\crstl.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
         