name: Compile Corsair Engine

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        config: [ release ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Project Files
        run: ./Linux.sh;
      - name: Linux Clang C++11
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_clang_c++11 -j$(nproc);
      - name: Linux Clang C++14
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_clang_c++14 -j$(nproc);
      - name: Linux GCC C++11
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_gcc_c++11 -j$(nproc);
      - name: Linux GCC C++14
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_gcc_c++14 -j$(nproc);
