name: Compile Corsair Engine

on: [push]

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        config: [ release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download 2017 Build Tools
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/15/release/vs_buildtools.exe" -OutFile "vs_buildtools_2017.exe"
      - name: Install VS2017 Build Tools
        run: |
          .\vs_buildtools_2017.exe --quiet --wait --norestart --nocache `
            --add Microsoft.VisualStudio.Workload.MSBuildTools `
            --add Microsoft.VisualStudio.Workload.VCTools `
            --includeRecommended
      - name: Generate Project Files
        run: ./'Visual Studio 2017.bat'
      - name: MSVC 2017
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 15.0
      - name: MSVC 2017 Release
        run: msbuild workspace/vs2017/crstl.sln -p:Configuration=Release -p:Platform="MSVC 64" -m

  linux:
    name: Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        config: [ release ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Project Files
        run: ./Linux.sh;
      - name: Linux Clang C++11
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_clang_c++11 -j$(nproc);
      - name: Linux Clang C++14
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_clang_c++14 -j$(nproc);
      - name: Linux GCC C++11
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_gcc_c++11 -j$(nproc);
      - name: Linux GCC C++14
        run: pushd workspace/gmake; make config=${{ matrix.config }}_linux64_gcc_c++14 -j$(nproc);
